### PR TITLE
incorporate ct-fetch from https://github.com/jcjones/ct-mapreduce

### PR DESCRIPTION
**Pull request by mozkeeler**

### CODE REVIEW

**Review by smarnach — APPROVED** [review]
Looks good to me.

Apparently CircleCI isn't reporting back the status to Github. We may need to authorize Circle CI, but I don't have admin permissions on this repo. Could you either take a look, or grant me the permissions?

**Comment by mozkeeler** [comment]
hmm - it doesn't look like I'm an admin on this repo either?
I had a quick look in circleci, and apparently there's a partial outage, so maybe that's the issue?

**Comment by mozkeeler** [comment]
... and after all that, I clicked squash and lost the  commit history anyway 🤦‍♀️

**Comment by smarnach** [comment]
Well, I guess we can fix that if we want to, by either `git revert`ing the squashed commit and then merging this PR again, or by removing the squashed commit by force-pushing to main.

**Pull request merged**
